<?php
/**
 * NowMovies - First-time setup wizard
 * Creates config.php with your TMDB API key and admin password.
 * This page is only accessible when config.php doesn't exist.
 */

$configPath = __DIR__ . '/config.php';

// If already configured, redirect to main page
if (file_exists($configPath)) {
    $msg = 'Already configured. Delete admin/config.php to reconfigure.';
    if ($_SERVER['REQUEST_METHOD'] === 'POST') {
        echo json_encode(['error' => $msg]);
        exit;
    }
    echo "<!DOCTYPE html><html><body style='font-family:sans-serif;text-align:center;padding:60px;'>
        <h2>NowMovies is already configured</h2>
        <p>$msg</p>
        <a href='../'>Go to NowMovies</a>
    </body></html>";
    exit;
}

// Handle form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    header('Content-Type: application/json');

    $apiKey = trim($_POST['api_key'] ?? '');
    $password = trim($_POST['password'] ?? '');

    if ($apiKey === '' || $password === '') {
        echo json_encode(['error' => 'Both fields are required.']);
        exit;
    }

    if (strlen($password) < 6) {
        echo json_encode(['error' => 'Password must be at least 6 characters.']);
        exit;
    }

    // Verify TMDB API key
    $testUrl = "https://api.themoviedb.org/3/movie/550?api_key=" . urlencode($apiKey);
    $ctx = stream_context_create(['ssl' => ['verify_peer' => false, 'verify_peer_name' => false], 'http' => ['timeout' => 10]]);
    $test = @file_get_contents($testUrl, false, $ctx);
    if ($test === false) {
        // Try curl fallback
        $escaped = '"' . str_replace('"', '', $testUrl) . '"';
        $test = shell_exec("curl -s -k --max-time 10 $escaped 2>nul");
    }

    if (!$test || strpos($test, '"id":550') === false) {
        echo json_encode(['error' => 'Invalid TMDB API key. Get one free at themoviedb.org/settings/api']);
        exit;
    }

    // Generate password hash
    $hash = password_hash($password, PASSWORD_BCRYPT);

    // Write config file
    $config = "<?php\n";
    $config .= "// NowMovies Configuration - Generated by setup wizard\n";
    $config .= "// Date: " . date('Y-m-d H:i:s') . "\n\n";
    $config .= "\$apiKey = " . var_export($apiKey, true) . ";\n";
    $config .= "\$adminPassword = " . var_export($hash, true) . ";\n";

    if (file_put_contents($configPath, $config) === false) {
        echo json_encode(['error' => 'Could not write config.php. Check folder permissions.']);
        exit;
    }

    // Create empty manifest if it doesn't exist
    $manifestPath = __DIR__ . '/../liste/manifest.json';
    if (!file_exists($manifestPath)) {
        $defaultManifest = [
            ['slug' => 'favourites', 'description' => 'My all-time favourite movies.', 'color' => '#ff3b30', 'protected' => true],
            ['slug' => 'watchlist', 'description' => 'Movies I want to watch.', 'color' => '#30d158', 'protected' => true],
        ];
        @mkdir(__DIR__ . '/../liste', 0755, true);
        file_put_contents($manifestPath, json_encode($defaultManifest, JSON_PRETTY_PRINT));
        // Create empty list files
        file_put_contents(__DIR__ . '/../liste/favourites.json', '{}');
        file_put_contents(__DIR__ . '/../liste/watchlist.json', '{}');
    }

    echo json_encode(['success' => true]);
    exit;
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NowMovies Setup</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: -apple-system, sans-serif; background: #f2f2f7; min-height: 100vh; display: flex; align-items: center; justify-content: center; }
        .card { background: #fff; border-radius: 16px; padding: 40px; max-width: 420px; width: 90%; box-shadow: 0 4px 24px rgba(0,0,0,0.08); }
        h1 { font-size: 1.6em; margin-bottom: 8px; }
        p { color: #8e8e93; margin-bottom: 24px; font-size: 0.9em; line-height: 1.5; }
        label { display: block; font-weight: 600; font-size: 0.85em; margin-bottom: 4px; margin-top: 16px; }
        input { width: 100%; padding: 10px 14px; border: 1px solid #d1d1d6; border-radius: 10px; font-size: 0.95em; font-family: inherit; }
        input:focus { outline: none; border-color: #007aff; }
        .hint { font-size: 0.78em; color: #8e8e93; margin-top: 4px; }
        .hint a { color: #007aff; }
        button { width: 100%; padding: 12px; margin-top: 24px; border: none; border-radius: 12px; background: #007aff; color: #fff; font-size: 1em; font-weight: 600; cursor: pointer; font-family: inherit; }
        button:hover { opacity: 0.9; }
        button:disabled { opacity: 0.5; cursor: not-allowed; }
        .msg { margin-top: 12px; padding: 10px; border-radius: 8px; font-size: 0.88em; display: none; }
        .msg.err { background: #fee2e2; color: #991b1b; display: block; }
        .msg.ok { background: #d1fae5; color: #065f46; display: block; }
    </style>
</head>
<body>
    <div class="card">
        <h1>Welcome to NowMovies</h1>
        <p>Set up your instance in 30 seconds. You need a free TMDB API key and a password for the admin panel.</p>

        <form id="setupForm">
            <label for="api_key">TMDB API Key</label>
            <input type="text" id="api_key" name="api_key" placeholder="Your TMDB API key..." required>
            <div class="hint">Free at <a href="https://www.themoviedb.org/settings/api" target="_blank">themoviedb.org/settings/api</a></div>

            <label for="password">Admin Password</label>
            <input type="password" id="password" name="password" placeholder="Min 6 characters" required minlength="6">
            <div class="hint">Used to manage your movie lists</div>

            <button type="submit" id="submitBtn">Set Up NowMovies</button>
        </form>

        <div id="msg" class="msg"></div>
    </div>

    <script>
    document.getElementById('setupForm').addEventListener('submit', async (e) => {
        e.preventDefault();
        const btn = document.getElementById('submitBtn');
        const msg = document.getElementById('msg');
        btn.disabled = true; btn.textContent = 'Setting up...';
        msg.className = 'msg'; msg.style.display = 'none';

        const fd = new FormData(e.target);
        try {
            const r = await fetch('setup.php', { method: 'POST', body: fd });
            const d = await r.json();
            if (d.success) {
                msg.className = 'msg ok'; msg.textContent = 'Setup complete! Redirecting...'; msg.style.display = 'block';
                setTimeout(() => window.location.href = '../', 1500);
            } else {
                msg.className = 'msg err'; msg.textContent = d.error; msg.style.display = 'block';
                btn.disabled = false; btn.textContent = 'Set Up NowMovies';
            }
        } catch (err) {
            msg.className = 'msg err'; msg.textContent = 'Connection error.'; msg.style.display = 'block';
            btn.disabled = false; btn.textContent = 'Set Up NowMovies';
        }
    });
    </script>
</body>
</html>
